### ISSUE TITLE
Criar uma Api Rest

### ISSUE THREAD

**Issue by alsgu3rra** [onixaeroportos/dashboard-ui#8]
<a name="readme-top"></a>

## Resumo

É necessário criar uma API Rest com o framework nestjs. Criar uma aplicação web utilizando o framework nestjs, esta aplicação deve fazer o papel de uma api rest que gerencia dados de aeroportos dentro do sistema onix.

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## Qual a utilidade da nova Feature

It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## Roadmap

- [X] Add App com Nestjs
- [X] Add Modulo Padrão com Service e Controller
- [X] Add Retorno de Mensagem "ok"
- [X] Add Configuração de testes unitários e e2e
- [X] Add Arquivo de Readme
- [X] Add Arquivo de licença do projeto
- [X] Add Arquivo de contribuição
- [X] Add Arquivo de histórico de atualizações
- [X] Add Arquivo de formatação prettier
- [X] Add Arquivo de eslint para padronizar
- [X] Add Configuração de variaveis de ambiente
- [X] Add Instalar pacotes npm
    - [X] Pacotes padrão do nestjs
    - [X] @nestjs/mapped-types

<p align="right">(<a href="#readme-top">back to top</a>)</p>
