### ISSUE TITLE
[TASK]: Templates de Arquivos

### ISSUE THREAD

**Issue by alsgu3rra** [onixaeroportos/dashboard-ui#9]
# ☕ Templates e Arquivos

é necessário alguns arquivos de templates para uma melhor organização e gestão do proejto.

## ☕ TO-DO

- [X] Template de issue para nova funcionalidade
- [X] Template de issue para bug na interface
- [X] Template de issue para nova tarefa
- [X] Template de pull request
- [x] Arquivo de Contribuidores do projeto
- [x] Template para notas de releases
- [x] Arquivo de segurança do projeto
